name: TitleAlerts
main: TitleAlerts\TitleAlerts
version: 1.0
api: [3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10]
load: STARTUP
author: EvolSoft
description: Show alerts in titles
website: https://www.evolsoft.tk
